DjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('layout/', include('layout.urls')),
    path('', RedirectView.as_view(url='layout/')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

layout/urls.py
from django.urls import path
from .views import HomeTemplate, ProjectTemplate, ContactTemplate, ThankYouTemplate
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'layout'

urlpatterns = [
	path('', HomeTemplate.as_view(), name='home'),
	path('projects/', ProjectTemplate.as_view(), name='projects'),
	path('contact/', ContactTemplate.as_view(), name='contact'),
	path('thank-you/', ThankYouTemplate.as_view(), name='thank-you'),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

layout/models.py
from django.db import models

# Create your models here.

layout/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse
import mimetypes
import os
from django.views.generic import TemplateView

# Create your views here.

class HomeTemplate(TemplateView):
	template_name = 'layout/home.html'


class ProjectTemplate(TemplateView):
	template_name = 'layout/projects.html'


class ContactTemplate(TemplateView):
	template_name = 'layout/contact.html'
	
class ThankYouTemplate(TemplateView):
	template_name = 'layout/thank-you.html'

DjangoApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Daniel Arpide</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Arvo:ital@0;1&display=swap"
      rel="stylesheet"
    />
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  </head>
  <body>
    <div class="main">
      <div class="main-container">
        <header class="header">
          <div class="container-table navigation">
            <a href="{% url "layout:home" %}" class="link-main">Home</a>
            <a href="{% url "layout:projects" %}" class="link-main">Projects</a>
          </div>
            <div class="col labels-social__links social">
              <a href="https://www.linkedin.com/in/daniel-j-arpide/"
                ><i class="fab fa-linkedin social"></i
              ></a>
              <a href="https://github.com/Edipra98"
                ><i class="fab fa-github-square social"></i
              ></a>
            </div>
        </header>
        
        {% block body %}{% endblock %}
      </div>
    </div>
    <footer class="footer">
      <div class="footer-container">
        <div>&copy; 2022 Daniel Arpide</div>
        <div>Contact Me: djarpide@gmail.com</div>
        <div class="col center-center labels social">
          <a href="https://www.linkedin.com/in/daniel-j-arpide/"
            ><i class="fab fa-linkedin social"></i
          ></a>
          <a href="https://github.com/Edipra98"
            ><i class="fab fa-github-square social"></i
          ></a>
        </div>
      </div>
    </footer>
  </body>
</html>

layout/templates/layout/contact.html
{% extends 'base.html' %} {% block body %}
<div class="container middle-align overlay">
	<form
		action="https://formsubmit.co/djarpide@gmail.com"
		method="POST"
		class="container middle-align"
	>
		<input type="text" name="name" placeholder="Name" class="form-style name" required />
		<input
			type="email"
			name="email"
			placeholder="Email Address"
			class="form-style email"
			required
		/>
		<input
			type="hidden"
			name="_next"
			value="https://edipra98.github.io/portfolio-site/thank-you.html"
		/>
		<textarea
			name="message"
			placeholder="Your Message Here"
			class="form-style message"
			required
		></textarea>
		<button type="submit" class="form-style btn">Send</button>
	</form>
</div>
{% endblock %}

layout/templates/layout/home.html
{% extends 'base.html' %} {% block body %}
<div class="quote">
	<div class="quote-inside">
		Many of life’s failures are people who did not realize how close
		they were to success when they gave up.
	</div>
	<div class="author">&mdash; Thomas A. Edison &mdash;</div>
</div>
<div class="about">
	<p class="about-me">About me:</p>
	<i class="tab"
		>&ensp;My name is Daniel Arpide, and I'm a graduate of Wentworth
		Institute of Technology with a degree in Computer Engineering, but
		have always had a stronger interest in the Computer Science
		portion of the curriculum. In college I worked with a team to
		develop an application using the Spotify API, while creating this
		I found out that programming was the path I wanted to take in my
		career. I am currently a junior software engineer focusing in web
		development.</i
	>
</div>
{% endblock body %}

layout/templates/layout/projects.html
{% extends 'base.html' %} {% load static %} {% block body %}
<div class="projects">
	<u><i>Projects</i></u>
</div>
<div class="works">
	<div class="col">
		<a href="https://edipra98.github.io/Main-SW-Characters/"
			><img
				src="https://images.unsplash.com/flagged/photo-1589829482673-03413c918c48?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=742&q=80"
				alt=""
				class="work-links"
		/></a>
		<div class="project">Main Star Wars Characters</div>

		<a
			href="https://github.com/Edipra98/Main-SW-Characters"
			class="code"
			>&lt;<span class="red-text">Code</span> /&gt;</a
		><a
			href="https://edipra98.github.io/Main-SW-Characters/"
			class="webpage"
			>&lt;<span class="red-text">Live Site</span> /&gt;</a
		>
	</div>
	<div class="col">
		<img
			src="https://images.unsplash.com/photo-1560109947-543149eceb16?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80"
			alt=""
			class="work-links"
		/>

		<div class="project">Movie Browser</div>

		<a href="https://github.com/Edipra98/moviebrowser" class="code"
			>&lt;<span class="red-text">Code</span> /&gt;</a
		>
	</div>
	<div class="col">
		<img
			src="{% static 'random_gen.png' %}"
			alt=""
			class="work-links"
		/>
		<div class="project">Random Character Generator</div>

		<a
			href="https://github.com/Edipra98/react-random-generator"
			class="code"
			>&lt;<span class="red-text">Code</span> /&gt;</a
		>
	</div>
</div>
{% endblock body %}

layout/templates/layout/thank-you.html
{% extends 'base.html' %} {% load static %} {% block body %}

<div class="thank-you">
	<div class="thank-you-text"><p>Thank you for contacting me. I will reply as soon as possible.</p></div>
</div>
{% endblock %}